apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spark-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tarunsraina/spark-app.git'  
    targetRevision: HEAD  
    path: manifests  
  destination:
    server: https://kubernetes.default.svc
    namespace: default  
  syncPolicy:
    automated: {}
