name: CI/CD Pipeline for Apache Spark App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.ACCESS_SECRET }}
        aws-region: ap-south-1  

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        echo "$(aws ecr get-login --no-include-email --region ap-south-1)" | sed 's|https://||'  

    - name: Build and push Docker image
      run: |
        docker build -t public.ecr.aws/d2r2f4i6/spark-app:latest .
        docker push public.ecr.aws/d2r2f4i6/spark-app:latest
